# Generated by Django 5.1.1 on 2024-09-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="просмотры"),
        ),
    ]
